const exampleData = {
    nodes: [
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHiS",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQHiS",
        },
        {
            color: "#3cb44b",
            id: "https://w3id.org/bot#Element",
            namespace: "https://w3id.org/bot#",
            body: "Element",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMMA",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMMA",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQM7v",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQM7v",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/0Twn90UZjBchfWScb6E5pp",
            namespace: "http://www.theproject.org/",
            body: "0Twn90UZjBchfWScb6E5pp",
        },
        {
            color: "#3cb44b",
            id: "https://w3id.org/bot#Space",
            namespace: "https://w3id.org/bot#",
            body: "Space",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMi7",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMi7",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMi6",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMi6",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQM7u",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQM7u",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMoz",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMoz",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMKR",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMKR",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMi8",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMi8",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/0Twn90UZjBchfWScb6E5py",
            namespace: "http://www.theproject.org/",
            body: "0Twn90UZjBchfWScb6E5py",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHch",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQHch",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHce",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQHce",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMW8",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMW8",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMan",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMan",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHeK",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQHeK",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMJ%24",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMJ$",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHiV",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQHiV",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHeg",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQHeg",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHdL",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQHdL",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            namespace: "http://www.theproject.org/",
            body: "2xmwjQJj55hujJUuTryQox",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMi2",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMi2",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMK6",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMK6",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMg%24",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMg$",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHiZ",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQHiZ",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQNKy",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQNKy",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMM8",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMM8",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHiU",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQHiU",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHiY",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQHiY",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQNAl",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQNAl",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMM9",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMM9",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMMD",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMMD",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQM9x",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQM9x",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHiT",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQHiT",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHgv",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQHgv",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHgc",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQHgc",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMUd",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMUd",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHi6",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQHi6",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMhN",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMhN",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHiK",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQHiK",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMfe",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMfe",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHWu",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQHWu",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMMC",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMMC",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMi4",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMi4",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMMF",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMMF",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMDH",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMDH",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHhN",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQHhN",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMiB",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMiB",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMMH",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMMH",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMi5",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMi5",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMiA",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMiA",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMoy",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMoy",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHWg",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQHWg",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMi9",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMi9",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMKI",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMKI",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMFq",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMFq",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMff",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMff",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHdb",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQHdb",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMoq",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMoq",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMMB",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMMB",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMUQ",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMUQ",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMiD",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQMiD",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2maDWV%242r93xx3TMOBQNKg",
            namespace: "http://www.theproject.org/",
            body: "2maDWV$2r93xx3TMOBQNKg",
        },
        {
            color: "#3cb44b",
            id: "https://w3id.org/bot#Storey",
            namespace: "https://w3id.org/bot#",
            body: "Storey",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2xmwjQJj55hujJUuUA3b9_",
            namespace: "http://www.theproject.org/",
            body: "2xmwjQJj55hujJUuUA3b9_",
        },
        {
            color: "#3cb44b",
            id: "https://w3id.org/bot#Site",
            namespace: "https://w3id.org/bot#",
            body: "Site",
        },
        {
            color: "#e6194b",
            id: "http://www.theproject.org/2xmwjQJj55hujJUuUA3b9z",
            namespace: "http://www.theproject.org/",
            body: "2xmwjQJj55hujJUuUA3b9z",
        },
        {
            color: "#3cb44b",
            id: "https://w3id.org/bot#Building",
            namespace: "https://w3id.org/bot#",
            body: "Building",
        },
    ],
    links: [
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHiS",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMMA",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQM7v",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/0Twn90UZjBchfWScb6E5pp",
            target: "https://w3id.org/bot#Space",
        },
        {
            id: "https://w3id.org/bot#containsElement",
            namespace: "https://w3id.org/bot#",
            body: "containsElement",
            source: "http://www.theproject.org/0Twn90UZjBchfWScb6E5pp",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQM7v",
        },
        {
            id: "https://w3id.org/bot#containsElement",
            namespace: "https://w3id.org/bot#",
            body: "containsElement",
            source: "http://www.theproject.org/0Twn90UZjBchfWScb6E5pp",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMi7",
        },
        {
            id: "https://w3id.org/bot#containsElement",
            namespace: "https://w3id.org/bot#",
            body: "containsElement",
            source: "http://www.theproject.org/0Twn90UZjBchfWScb6E5pp",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMi6",
        },
        {
            id: "https://w3id.org/bot#containsElement",
            namespace: "https://w3id.org/bot#",
            body: "containsElement",
            source: "http://www.theproject.org/0Twn90UZjBchfWScb6E5pp",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQM7u",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMoz",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMKR",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMi8",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/0Twn90UZjBchfWScb6E5py",
            target: "https://w3id.org/bot#Space",
        },
        {
            id: "https://w3id.org/bot#containsElement",
            namespace: "https://w3id.org/bot#",
            body: "containsElement",
            source: "http://www.theproject.org/0Twn90UZjBchfWScb6E5py",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHch",
        },
        {
            id: "https://w3id.org/bot#containsElement",
            namespace: "https://w3id.org/bot#",
            body: "containsElement",
            source: "http://www.theproject.org/0Twn90UZjBchfWScb6E5py",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHce",
        },
        {
            id: "https://w3id.org/bot#containsElement",
            namespace: "https://w3id.org/bot#",
            body: "containsElement",
            source: "http://www.theproject.org/0Twn90UZjBchfWScb6E5py",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMW8",
        },
        {
            id: "https://w3id.org/bot#containsElement",
            namespace: "https://w3id.org/bot#",
            body: "containsElement",
            source: "http://www.theproject.org/0Twn90UZjBchfWScb6E5py",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMan",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMi7",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHeK",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMJ%24",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHiV",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHeg",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHdL",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHiS",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMMA",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMoz",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMKR",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMi8",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHeK",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMJ%24",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHiV",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHeg",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHdL",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMi2",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMK6",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMg%24",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHiZ",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQNKy",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMM8",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHiU",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHiY",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQNAl",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMM9",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMMD",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQM9x",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHiT",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHgv",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHgc",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMUd",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHi6",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMhN",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHiK",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMfe",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHWu",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMMC",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMi4",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMMF",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMDH",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHhN",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMiB",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMMH",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMi5",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMiA",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMoy",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHWg",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMi9",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMKI",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMFq",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMff",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHdb",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMoq",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMMB",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMUQ",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMiD",
        },
        {
            id: "https://w3id.org/bot#hasElement",
            namespace: "https://w3id.org/bot#",
            body: "hasElement",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/2maDWV%242r93xx3TMOBQNKg",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "https://w3id.org/bot#Storey",
        },
        {
            id: "https://w3id.org/bot#hasSpace",
            namespace: "https://w3id.org/bot#",
            body: "hasSpace",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/0Twn90UZjBchfWScb6E5pp",
        },
        {
            id: "https://w3id.org/bot#hasSpace",
            namespace: "https://w3id.org/bot#",
            body: "hasSpace",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
            target: "http://www.theproject.org/0Twn90UZjBchfWScb6E5py",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMi2",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMK6",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMg%24",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHiZ",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQNKy",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMM8",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHiU",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHiY",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQNAl",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuUA3b9_",
            target: "https://w3id.org/bot#Site",
        },
        {
            id: "https://w3id.org/bot#hasBuilding",
            namespace: "https://w3id.org/bot#",
            body: "hasBuilding",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuUA3b9_",
            target: "http://www.theproject.org/2xmwjQJj55hujJUuUA3b9z",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMM9",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMMD",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQM9x",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHiT",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHgv",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHgc",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMUd",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHch",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHi6",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMhN",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMi6",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHiK",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMfe",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHWu",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMMC",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMi4",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMMF",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMDH",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHhN",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHce",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMiB",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMMH",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMi5",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMiA",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMoy",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuUA3b9z",
            target: "https://w3id.org/bot#Building",
        },
        {
            id: "https://w3id.org/bot#hasStorey",
            namespace: "https://w3id.org/bot#",
            body: "hasStorey",
            source: "http://www.theproject.org/2xmwjQJj55hujJUuUA3b9z",
            target: "http://www.theproject.org/2xmwjQJj55hujJUuTryQox",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHWg",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMi9",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMKI",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMFq",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMW8",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMff",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQHdb",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMan",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMoq",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMMB",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMUQ",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQMiD",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQM7u",
            target: "https://w3id.org/bot#Element",
        },
        {
            id: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            namespace: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            body: "type",
            source: "http://www.theproject.org/2maDWV%242r93xx3TMOBQNKg",
            target: "https://w3id.org/bot#Element",
        },
    ],
};

export { exampleData };
