const exampleData = {
    nodes: [...Array(14).keys()].map((i) => ({ id: i })),
    links: [
        { source: 0, target: 1, curvature: 0 },
        { source: 0, target: 1, curvature: 0.8 },
        { source: 0, target: 1, curvature: 0.8 },
        { source: 0, target: 1, curvature: 0.8 },
        { source: 0, target: 1, curvature: 0.8 },
        { source: 0, target: 1, curvature: 0.8 },
        { source: 0, target: 1, curvature: 0.8 },
        { source: 0, target: 1, curvature: 0.8 },
        { source: 0, target: 1, curvature: 0.8 },
        { source: 0, target: 1, curvature: 0.8 },
        { source: 0, target: 1, curvature: 0.8 },
        { source: 0, target: 1, curvature: 0.8 },
        { source: 0, target: 1, curvature: 0.8 },
        { source: 2, target: 3, curvature: 0.4 },
        { source: 3, target: 2, curvature: 0.4 },
        { source: 2, target: 3, curvature: 0.4 },
        { source: 3, target: 2, curvature: 0.4 },
        { source: 4, target: 4, curvature: 0.3 },
        { source: 4, target: 4, curvature: 0.3 },
        { source: 4, target: 4, curvature: 0.3 },
        { source: 5, target: 6, curvature: 0 },
        { source: 5, target: 5, curvature: 0.5 },
        { source: 6, target: 6, curvature: -0.5 },
        { source: 7, target: 8, curvature: 0.2 },
        { source: 8, target: 9, curvature: 0.5 },
        { source: 9, target: 10, curvature: 0.7 },
        { source: 10, target: 11, curvature: 0.2 },
        { source: 11, target: 12, curvature: 0.1 },
        { source: 12, target: 7, curvature: 0.6 },
        { source: 13, target: 13, curvature: 0.1 },
        { source: 13, target: 13, curvature: 0.2 },
        { source: 13, target: 13, curvature: 0.5 },
        { source: 13, target: 13, curvature: 0.7 },
        { source: 13, target: 13, curvature: 0.2 },
    ],
};

export { exampleData };
