on:
  pull_request:
    types: [closed]
    branches:
      - master
    # Only run on merge
    conditions: >
      github.event.pull_request.merged == true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.19.1'
          
      - name: Install dependencies
        run: npm install
      
      - name: Build and deploy site
        run: npm run build && npx gh-pages -d dist
